name: DevTools
version: '${project.version}'
main: de.floxyi.devtools.Devtools
api-version: 1.18
authors: [ Floxyi ]
description: Tools to make the life of a Java Plugin Developer way easier!

commands:
  location:
    description: Get the location of a player or a block and use it in your code (/location <player "player name"> <block "player name"> <view "player name">)
  sound:
    description: Plays the specified sound in a custom volume and pitch (/sound "sound name" <volume pitch>)
  fly:
    description: Allows the player to fly in a specified speed (/fly "speed")