name: DevTools
version: '${project.version}'
main: de.floxyi.devtools.Devtools
api-version: 1.17
authors: [ Floxyi ]
description: A useful Minecraft Plugin for Java Plugin Developers

commands:
  location:
    description: Makes a console log with the current location's declaration for Java
  sound:
    description: Plays the specified sound